"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShapeDrawCommandVertex = exports.ShapeDrawCommand = exports.Shape = exports.SupercellSWF = exports.CompressionSignature = exports.SupercellCompression = void 0;
var SuperecllCompression_1 = require("./node/SuperecllCompression");
Object.defineProperty(exports, "SupercellCompression", { enumerable: true, get: function () { return SuperecllCompression_1.SupercellCompression; } });
Object.defineProperty(exports, "CompressionSignature", { enumerable: true, get: function () { return SuperecllCompression_1.CompressionSignature; } });
var SupercellFlash_1 = require("./node/SupercellFlash");
Object.defineProperty(exports, "SupercellSWF", { enumerable: true, get: function () { return SupercellFlash_1.SupercellSWF; } });
Object.defineProperty(exports, "Shape", { enumerable: true, get: function () { return SupercellFlash_1.Shape; } });
Object.defineProperty(exports, "ShapeDrawCommand", { enumerable: true, get: function () { return SupercellFlash_1.ShapeDrawCommand; } });
Object.defineProperty(exports, "ShapeDrawCommandVertex", { enumerable: true, get: function () { return SupercellFlash_1.ShapeDrawCommandVertex; } });
